require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataFileUploadsController do

  # This should return the minimal set of attributes required to create a valid
  # DataFileUpload. As you add validations to DataFileUpload, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataFileUploadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all data_file_uploads as @data_file_uploads" do
      data_file_upload = DataFileUpload.create! valid_attributes
      get :index, {}, valid_session
      assigns(:data_file_uploads).should eq([data_file_upload])
    end
  end

  describe "GET show" do
    it "assigns the requested data_file_upload as @data_file_upload" do
      data_file_upload = DataFileUpload.create! valid_attributes
      get :show, {:id => data_file_upload.to_param}, valid_session
      assigns(:data_file_upload).should eq(data_file_upload)
    end
  end

  describe "GET new" do
    it "assigns a new data_file_upload as @data_file_upload" do
      get :new, {}, valid_session
      assigns(:data_file_upload).should be_a_new(DataFileUpload)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_file_upload as @data_file_upload" do
      data_file_upload = DataFileUpload.create! valid_attributes
      get :edit, {:id => data_file_upload.to_param}, valid_session
      assigns(:data_file_upload).should eq(data_file_upload)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataFileUpload" do
        expect {
          post :create, {:data_file_upload => valid_attributes}, valid_session
        }.to change(DataFileUpload, :count).by(1)
      end

      it "assigns a newly created data_file_upload as @data_file_upload" do
        post :create, {:data_file_upload => valid_attributes}, valid_session
        assigns(:data_file_upload).should be_a(DataFileUpload)
        assigns(:data_file_upload).should be_persisted
      end

      it "redirects to the created data_file_upload" do
        post :create, {:data_file_upload => valid_attributes}, valid_session
        response.should redirect_to(DataFileUpload.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_file_upload as @data_file_upload" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataFileUpload.any_instance.stub(:save).and_return(false)
        post :create, {:data_file_upload => {  }}, valid_session
        assigns(:data_file_upload).should be_a_new(DataFileUpload)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataFileUpload.any_instance.stub(:save).and_return(false)
        post :create, {:data_file_upload => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_file_upload" do
        data_file_upload = DataFileUpload.create! valid_attributes
        # Assuming there are no other data_file_uploads in the database, this
        # specifies that the DataFileUpload created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataFileUpload.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => data_file_upload.to_param, :data_file_upload => { "these" => "params" }}, valid_session
      end

      it "assigns the requested data_file_upload as @data_file_upload" do
        data_file_upload = DataFileUpload.create! valid_attributes
        put :update, {:id => data_file_upload.to_param, :data_file_upload => valid_attributes}, valid_session
        assigns(:data_file_upload).should eq(data_file_upload)
      end

      it "redirects to the data_file_upload" do
        data_file_upload = DataFileUpload.create! valid_attributes
        put :update, {:id => data_file_upload.to_param, :data_file_upload => valid_attributes}, valid_session
        response.should redirect_to(data_file_upload)
      end
    end

    describe "with invalid params" do
      it "assigns the data_file_upload as @data_file_upload" do
        data_file_upload = DataFileUpload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataFileUpload.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_file_upload.to_param, :data_file_upload => {  }}, valid_session
        assigns(:data_file_upload).should eq(data_file_upload)
      end

      it "re-renders the 'edit' template" do
        data_file_upload = DataFileUpload.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataFileUpload.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_file_upload.to_param, :data_file_upload => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_file_upload" do
      data_file_upload = DataFileUpload.create! valid_attributes
      expect {
        delete :destroy, {:id => data_file_upload.to_param}, valid_session
      }.to change(DataFileUpload, :count).by(-1)
    end

    it "redirects to the data_file_uploads list" do
      data_file_upload = DataFileUpload.create! valid_attributes
      delete :destroy, {:id => data_file_upload.to_param}, valid_session
      response.should redirect_to(data_file_uploads_url)
    end
  end

end
